"""description of changes

Revision ID: 6849f00015dd
Revises: bd88567e0059
Create Date: 2025-10-22 23:14:08.739763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6849f00015dd'
down_revision: Union[str, Sequence[str], None] = 'bd88567e0059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('department_id', sa.Integer(), nullable=False))
    op.add_column('employees', sa.Column('email', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('phone', sa.String(), nullable=True))
    op.alter_column('employees', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'position_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_foreign_key(None, 'employees', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.alter_column('employees', 'position_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('employees', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('employees', 'phone')
    op.drop_column('employees', 'email')
    op.drop_column('employees', 'department_id')
    # ### end Alembic commands ###
